added initial create shopping list page
rsun0/GroceryBuddy pull request #65
Opened 2019-03-10 23:17 UTC by mongy910

## Status: 

:construction: In development

## Description
The initial version of the create shopping list page

Related issues: #56 

## Todos

## Screenshots

2019-03-10 23:51 UTC, davidenwang requested changes
Not bad you're nasty 🤢keep up the good work and just do a quick var to let change

2019-03-10 23:51 UTC, Davidw1339 commented on frontend/pages/SearchPage.js
> +    for (var i = 0; i < this.state.itemList.length; i++) {
change var to let

2019-03-10 23:51 UTC, Davidw1339 commented on frontend/pages/SearchPage.js
> +        <ItemSearchBar onSearch={this.submitSearch} />
looks good 📜

2019-03-10 23:51 UTC, Davidw1339 commented on frontend/pages/SearchPage.js
> +          <Button
good job with the ✨ button ✨ i like the icon

2019-03-10 23:53 UTC, mongy910 commented on frontend/pages/SearchPage.js
> +    for (var i = 0; i < this.state.itemList.length; i++) {
got it

2019-03-11 00:18 UTC, davidenwang approved these changes

2019-03-11 00:18 UTC, merged